### ISSUE TITLE
[SEARCH BAR] [REQUIRED] Search Bar

### ISSUE THREAD

**Issue by nmachado26** [FBU-2018-jalvarado/item-share-app#4]

**Comment by Stephanielpt** [comment]
- results automatically start populating (autofill)
- each cell presents the item (name) from database)

**Comment by tar-singh** [comment]
- when search cell chosen, it presents the respective pins on the map
- only shows table view when search bar tapped
- Clicking on item cell segues to map, sending the item through the segue to MapViewController

**Comment by tar-singh** [comment]
- capital case autofill done
